/*
  99: Final Capstone Project - Answers
*/

-- Task 1: Calculate the total revenue generated by each country
SELECT 
    c.country, 
    SUM(o.total_amount) as total_revenue
FROM cap_customers c
JOIN cap_orders o ON c.customer_id = o.customer_id
GROUP BY c.country
ORDER BY total_revenue DESC;

-- Task 2: Top 3 best-selling product categories by total quantity sold
SELECT 
    p.category, 
    SUM(oi.quantity) as total_quantity
FROM cap_products p
JOIN cap_order_items oi ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY total_quantity DESC
LIMIT 3;

-- Task 3: Identify "Whales" (spent > $5000)
SELECT 
    c.customer_id, 
    c.name, 
    SUM(o.total_amount) as total_spent
FROM cap_customers c
JOIN cap_orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
HAVING SUM(o.total_amount) > 5000;

-- Task 4: Total Profit per Product
SELECT 
    p.name,
    SUM((oi.price_at_purchase - p.cost) * oi.quantity) as total_profit
FROM cap_products p
JOIN cap_order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.name;

-- Task 5: Month with highest user signups
SELECT 
    DATE_FORMAT(signup_date, '%Y-%m') as signup_month,
    COUNT(customer_id) as total_signups
FROM cap_customers
GROUP BY signup_month
ORDER BY total_signups DESC
LIMIT 1;

-- Cleanup
DROP TABLE cap_order_items;
DROP TABLE cap_orders;
DROP TABLE cap_products;
DROP TABLE cap_customers;
