/*
  99: Final Capstone Project
  
  Welcome to your Final SQL Assessment. 
  This mimics a real-world dataset for an e-commerce platform.
  
  Schema Overview:
  1. `customers` (customer_id, name, signup_date, country)
  2. `orders` (order_id, customer_id, order_date, total_amount)
  3. `order_items` (order_item_id, order_id, product_id, quantity, price_at_purchase)
  4. `products` (product_id, name, category, cost)
  
  TASKS:
  1. Calculate the total revenue generated by each country, ordered highest to lowest.
  2. Find the top 3 best-selling product categories by total quantity sold.
  3. Identify "Whales" - Customers who have spent more than $5,000 in total.
  4. Calculate the Profit Margin for each order item (price_at_purchase - cost) * quantity, and roll it up to Total Profit per Product.
  5. Find the month with the highest user signups.
*/

-- (Setup Script for the Capstone Environment)
CREATE TABLE IF NOT EXISTS cap_customers (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    signup_date DATE,
    country VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS cap_products (
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    category VARCHAR(50),
    cost DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS cap_orders (
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    total_amount DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS cap_order_items (
    order_item_id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    price_at_purchase DECIMAL(10,2)
);

-- Seed Data (Shortened for example)
INSERT INTO cap_customers (name, signup_date, country) VALUES 
('Alice', '2023-01-15', 'USA'), ('Bob', '2023-02-20', 'UK'), ('Charlie', '2023-01-25', 'USA');

INSERT INTO cap_products (name, category, cost) VALUES 
('Laptop', 'Electronics', 500.00), ('Desk', 'Furniture', 100.00), ('Mouse', 'Electronics', 10.00);

INSERT INTO cap_orders (customer_id, order_date, total_amount) VALUES 
(1, '2023-03-01', 1200.00), (2, '2023-03-05', 150.00), (1, '2023-04-10', 5200.00);

INSERT INTO cap_order_items (order_id, product_id, quantity, price_at_purchase) VALUES 
(1, 1, 1, 1000.00), (1, 2, 1, 200.00), (2, 2, 1, 150.00), (3, 1, 5, 1000.00), (3, 3, 10, 20.00);

-- WRITE YOUR QUERIES BELOW:

-- Task 1: 

-- Task 2: 

-- Task 3: 

-- Task 4: 

-- Task 5: 

